# Generated by Django 2.2.8 on 2020-09-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsplugin',
            name='auth_only',
            field=models.BooleanField(default=False, verbose_name='show auth users only'),
        ),
    ]
