# Generated by Django 2.2.17 on 2021-07-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_cmsplugin_auth_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsplugin',
            name='cols_height',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, verbose_name='plugin height'),
        ),
        migrations.AddField(
            model_name='cmsplugin',
            name='cols_start',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, verbose_name='plugin start column'),
        ),
        migrations.AddField(
            model_name='cmsplugin',
            name='cols_width',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, verbose_name='plugin width'),
        ),
        migrations.AlterField(
            model_name='cmsplugin',
            name='auth_only',
            field=models.BooleanField(default=False, verbose_name='show for auth users only'),
        ),
    ]
