# Generated by Django 2.2.17 on 2021-08-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_cols'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsplugin',
            name='cell_vertical',
            field=models.CharField(choices=[('start', 'start'), ('center', 'center'), ('end', 'end')], default='start', max_length=16, verbose_name='vertical align'),
        ),
        migrations.AlterField(
            model_name='cmsplugin',
            name='cols_height',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='cmsplugin',
            name='cols_start',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, verbose_name='start column'),
        ),
        migrations.AlterField(
            model_name='cmsplugin',
            name='cols_width',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, verbose_name='width'),
        ),
    ]
